package com.hms.prescription.service;

import com.hms.common.exception.AllergyHardStopException;
import com.hms.patient.domain.Gender;
import com.hms.patient.dto.PatientRegistrationRequest;
import com.hms.patient.history.domain.AllergySeverity;
import com.hms.patient.history.dto.AllergyDto;
import com.hms.patient.history.dto.PatientHistoryRequest;
import com.hms.patient.history.service.PatientHistoryService;
import com.hms.patient.service.PatientService;
import com.hms.prescription.domain.FoodInstruction;
import com.hms.prescription.dto.DrugInteractionCheckRequest;
import com.hms.prescription.dto.DrugInteractionCheckResponse;
import com.hms.prescription.dto.DrugResponse;
import com.hms.prescription.dto.PrescriptionItemRequest;
import com.hms.prescription.dto.PrescriptionRequest;
import com.hms.prescription.dto.PrescriptionResponse;
import com.hms.prescription.dto.TemplateResponse;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import java.time.LocalDate;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.assertj.core.api.Assertions.offset;

@SpringBootTest
@ActiveProfiles("test")
class PrescriptionServiceIntegrationTest {

    @Autowired
    private PrescriptionService prescriptionService;

    @Autowired
    private DrugService drugService;

    @Autowired
    private TemplateService templateService;

    @Autowired
    private PatientService patientService;

    @Autowired
    private PatientHistoryService patientHistoryService;

    private String registerPatient(String contactNumber, LocalDate dateOfBirth) {
        PatientRegistrationRequest request = new PatientRegistrationRequest(
                null, "Prescription Test Patient", dateOfBirth, Gender.MALE, null, null,
                "Indian", null, null, null, contactNumber, null, null, null, null,
                null, null, null, null, null
        );
        return patientService.register(request).upid();
    }

    private Long drugIdFor(String genericName) {
        return drugService.search(genericName).stream()
                .filter(d -> d.genericName().equalsIgnoreCase(genericName))
                .findFirst()
                .orElseThrow()
                .id();
    }

    @Test
    void listsElevenTemplatesWithSuggestedDrugs() {
        List<TemplateResponse> templates = templateService.listTemplates();

        assertThat(templates).hasSize(11);
        TemplateResponse pud = templates.stream().filter(t -> t.name().equals("PUD")).findFirst().orElseThrow();
        assertThat(pud.suggestedDrugs()).extracting(DrugResponse::genericName).contains("Omeprazole");
    }

    @Test
    void createsPrescriptionWithAutoGeneratedInstructions() {
        String patientId = registerPatient("9888800001", LocalDate.of(1985, 5, 5));
        Long omeprazoleId = drugIdFor("Omeprazole");

        PrescriptionRequest request = new PrescriptionRequest(
                patientId, 901L, null, "Dr. Sharma", "Dr. Sharma - signed",
                null,
                List.of(new PrescriptionItemRequest(omeprazoleId, "20mg", "once daily", "Oral", 14,
                        FoodInstruction.BEFORE_FOOD, 1, null))
        );

        PrescriptionResponse response = prescriptionService.create(request);

        assertThat(response.items().get(0).generatedInstructions())
                .isEqualTo("Take 20mg of Omeprazole via Oral route once daily before food for 14 days.");
        assertThat(response.items().get(0).refillsAllowed()).isEqualTo(1);
        assertThat(response.items().get(0).refillsUsed()).isEqualTo(0);
    }

    @Test
    void rejectsPrescriptionForHardStopAllergy() {
        String patientId = registerPatient("9888800002", LocalDate.of(1990, 1, 1));
        Long amoxicillinId = drugIdFor("Amoxicillin");

        patientHistoryService.create(new PatientHistoryRequest(
                patientId,
                null, null,
                List.of(), List.of(), List.of(),
                List.of(new AllergyDto("Amoxicillin", "Anaphylaxis", AllergySeverity.ANAPHYLAXIS, true)),
                List.of(),
                null, null,
                null, null, null, null, null,
                null, null, null, null, null, null, null, null, null, null,
                null, null));

        PrescriptionRequest request = new PrescriptionRequest(
                patientId, 902L, null, "Dr. Rao", "Dr. Rao - signed", null,
                List.of(new PrescriptionItemRequest(amoxicillinId, "500mg", "twice daily", "Oral", 7, null, null, null)));

        assertThatThrownBy(() -> prescriptionService.create(request))
                .isInstanceOf(AllergyHardStopException.class);
    }

    @Test
    void detectsDrugInteractionBetweenPrescriptionItems() {
        String patientId = registerPatient("9888800003", LocalDate.of(1978, 3, 3));
        Long omeprazoleId = drugIdFor("Omeprazole");
        Long clopidogrelId = drugIdFor("Clopidogrel");

        PrescriptionRequest request = new PrescriptionRequest(
                patientId, 903L, null, "Dr. Iyer", "Dr. Iyer - signed", null,
                List.of(
                        new PrescriptionItemRequest(omeprazoleId, "20mg", "once daily", "Oral", 30, null, null, null),
                        new PrescriptionItemRequest(clopidogrelId, "75mg", "once daily", "Oral", 30, null, null, null)
                ));

        PrescriptionResponse response = prescriptionService.create(request);

        assertThat(response.interactionWarnings()).isNotEmpty();
    }

    @Test
    void surfacesNutritionAlertForOmeprazole() {
        String patientId = registerPatient("9888800004", LocalDate.of(1988, 6, 6));
        Long omeprazoleId = drugIdFor("Omeprazole");

        PrescriptionRequest request = new PrescriptionRequest(
                patientId, 904L, null, "Dr. Nair", "Dr. Nair - signed", null,
                List.of(new PrescriptionItemRequest(omeprazoleId, "20mg", "once daily", "Oral", 14, null, null, null)));

        PrescriptionResponse response = prescriptionService.create(request);

        assertThat(response.nutritionAlerts()).extracting(a -> a.drugName()).contains("Omeprazole");
    }

    @Test
    void calculatesPediatricDoseForYoungPatient() {
        String patientId = registerPatient("9888800005", LocalDate.now().minusYears(5));
        Long paracetamolId = drugIdFor("Paracetamol");

        PrescriptionRequest request = new PrescriptionRequest(
                patientId, 905L, null, "Dr. Verma", "Dr. Verma - signed", null,
                List.of(new PrescriptionItemRequest(paracetamolId, "as calculated", "every 6 hours", "Oral", 3,
                        null, null, 20.0)));

        PrescriptionResponse response = prescriptionService.create(request);

        assertThat(response.items().get(0).calculatedPediatricDoseMg()).isCloseTo(300.0, offset(0.01));
    }

    @Test
    void doesNotCalculatePediatricDoseForAdultPatient() {
        String patientId = registerPatient("9888800006", LocalDate.of(1980, 1, 1));
        Long paracetamolId = drugIdFor("Paracetamol");

        PrescriptionRequest request = new PrescriptionRequest(
                patientId, 906L, null, "Dr. Verma", "Dr. Verma - signed", null,
                List.of(new PrescriptionItemRequest(paracetamolId, "500mg", "every 6 hours", "Oral", 3,
                        null, null, 70.0)));

        PrescriptionResponse response = prescriptionService.create(request);

        assertThat(response.items().get(0).calculatedPediatricDoseMg()).isNull();
    }

    @Test
    void checksInteractionsStandaloneWithoutCreatingPrescription() {
        Long omeprazoleId = drugIdFor("Omeprazole");
        Long clopidogrelId = drugIdFor("Clopidogrel");

        DrugInteractionCheckResponse response = prescriptionService.checkInteractions(
                new DrugInteractionCheckRequest(List.of(omeprazoleId, clopidogrelId), null));

        assertThat(response.interactionWarnings()).isNotEmpty();
    }

    @Test
    void listsPrescriptionsForPatient() {
        String patientId = registerPatient("9888800007", LocalDate.of(1995, 2, 2));
        Long omeprazoleId = drugIdFor("Omeprazole");

        prescriptionService.create(new PrescriptionRequest(
                patientId, 907L, null, "Dr. Kapoor", "Dr. Kapoor - signed", null,
                List.of(new PrescriptionItemRequest(omeprazoleId, "20mg", "once daily", "Oral", 14, null, null, null))));

        List<PrescriptionResponse> results = prescriptionService.getByPatientId(patientId);

        assertThat(results).hasSize(1);
    }
}
