package com.hms.diagnosis.domain;

public enum IcdCategory {
    PEPTIC_ULCER_DISEASE,
    GASTRITIS,
    ESOPHAGEAL_DISORDER,
    GASTRIC_DISORDER,
    APPENDICITIS,
    INFLAMMATORY_BOWEL_DISEASE,
    GASTROENTERITIS,
    DIVERTICULAR_DISEASE,
    FUNCTIONAL_BOWEL_DISORDER,
    ANORECTAL_DISORDER
}
