CREATE TABLE drugs (
    id                          BIGINT AUTO_INCREMENT PRIMARY KEY,
    generic_name                VARCHAR(255)    NOT NULL,
    brand_name                  VARCHAR(255)    NULL,
    category                    VARCHAR(30)     NOT NULL,
    unit                        VARCHAR(15)     NOT NULL,
    strength                    VARCHAR(50)     NULL,
    route_of_administration     VARCHAR(50)     NULL,
    schedule                    VARCHAR(5)      NULL,
    contraindications           VARCHAR(500)    NULL,
    drug_interactions           VARCHAR(500)    NULL,
    pediatric_dose_mg_per_kg    DOUBLE          NULL,
    adult_dose                  VARCHAR(255)    NULL,
    geriatric_dose              VARCHAR(255)    NULL,
    maximum_daily_dose          VARCHAR(100)    NULL,
    nutrition_interaction       VARCHAR(500)    NULL,
    side_effects                VARCHAR(500)    NULL,
    is_active                   BOOLEAN         NOT NULL DEFAULT TRUE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE INDEX idx_drugs_generic_name ON drugs (generic_name);
CREATE INDEX idx_drugs_category ON drugs (category);

INSERT INTO drugs (generic_name, brand_name, category, unit, strength, route_of_administration, schedule,
    contraindications, drug_interactions, pediatric_dose_mg_per_kg, adult_dose, geriatric_dose, maximum_daily_dose,
    nutrition_interaction, side_effects, is_active) VALUES
('Omeprazole', 'Omez', 'PPI', 'CAPSULE', '20mg', 'Oral', 'H1',
    'Hypersensitivity to PPIs', 'Clopidogrel', 1.0, '20mg once daily', '20mg once daily', '40mg',
    'Take on empty stomach, 30 minutes before food', 'Headache, diarrhea', TRUE),
('Pantoprazole', 'Pantocid', 'PPI', 'TABLET', '40mg', 'Oral', 'H1',
    'Hypersensitivity to PPIs', NULL, NULL, '40mg once daily', '40mg once daily', '80mg',
    'Take before breakfast', 'Nausea, headache', TRUE),
('Famotidine', 'Famocid', 'H2_BLOCKER', 'TABLET', '40mg', 'Oral', 'H1',
    'Hypersensitivity to H2 blockers', NULL, 0.5, '40mg once daily', '20mg once daily', '80mg',
    NULL, 'Dizziness, constipation', TRUE),
('Aluminium Hydroxide + Magnesium Hydroxide', 'Digene', 'ANTACID', 'SYRUP', '200mg/5ml', 'Oral', NULL,
    'Severe renal impairment', NULL, NULL, '10-20ml after meals', '10ml after meals', '80ml',
    NULL, 'Diarrhea, constipation', TRUE),
('Sucralfate', 'Sucrafil', 'ANTACID', 'SYRUP', '1g/10ml', 'Oral', NULL,
    NULL, NULL, NULL, '10ml four times daily', '10ml four times daily', '40ml',
    'Take on empty stomach, 1 hour before meals', 'Constipation', TRUE),
('Amoxicillin', 'Mox', 'H_PYLORI_ERADICATION', 'CAPSULE', '500mg', 'Oral', 'H1',
    'Penicillin allergy', 'Methotrexate', 25.0, '1g twice daily', '500mg twice daily', '2g',
    NULL, 'Rash, diarrhea', TRUE),
('Clarithromycin', 'Claribid', 'H_PYLORI_ERADICATION', 'TABLET', '500mg', 'Oral', 'H1',
    'Macrolide allergy, QT prolongation', 'Statins', NULL, '500mg twice daily', '500mg twice daily', '1g',
    NULL, 'Taste disturbance, GI upset', TRUE),
('Domperidone', 'Domstal', 'PROKINETIC', 'TABLET', '10mg', 'Oral', 'H1',
    'Prolactinoma, cardiac arrhythmia', NULL, 0.25, '10mg thrice daily before meals', '10mg twice daily', '30mg',
    'Take before meals', 'Dry mouth', TRUE),
('Mesalamine', 'Mesacol', 'FIVE_ASA', 'TABLET', '400mg', 'Oral', 'H1',
    'Salicylate hypersensitivity', NULL, NULL, '800mg thrice daily', '400mg thrice daily', '4.8g',
    NULL, 'Headache, flatulence', TRUE),
('Azathioprine', 'Imuran', 'IMMUNOMODULATOR', 'TABLET', '50mg', 'Oral', 'H1',
    'Pregnancy, active infection', 'Allopurinol', NULL, '2-2.5mg/kg once daily', '50mg once daily', '150mg',
    NULL, 'Bone marrow suppression, nausea', TRUE),
('Infliximab', 'Remicade', 'BIOLOGIC', 'INJECTION', '100mg', 'IV', 'H1',
    'Active tuberculosis, heart failure', NULL, NULL, '5mg/kg IV infusion', '5mg/kg IV infusion', '10mg/kg',
    NULL, 'Infusion reaction, infection risk', TRUE),
('Adalimumab', 'Humira', 'BIOLOGIC', 'INJECTION', '40mg', 'Injection', 'H1',
    'Active tuberculosis', NULL, NULL, '40mg subcutaneous every 2 weeks', '40mg every 2 weeks', '40mg',
    NULL, 'Injection site reaction, infection risk', TRUE),
('Prednisolone', 'Wysolone', 'CORTICOSTEROID', 'TABLET', '10mg', 'Oral', 'H1',
    'Systemic fungal infection', 'NSAIDs', 1.0, '40mg once daily tapering', '20mg once daily', '60mg',
    'Take with food', 'Weight gain, hyperglycemia', TRUE),
('Normal Saline 0.9%', 'NS', 'IV_FLUID', 'IV', '500ml', 'IV', NULL,
    'Fluid overload', NULL, NULL, 'As per clinical requirement', 'As per clinical requirement', '3000ml',
    NULL, 'Fluid overload if over-infused', TRUE),
('Paracetamol', 'Crocin', 'ANALGESIC', 'TABLET', '500mg', 'Oral', NULL,
    'Severe hepatic impairment', 'Warfarin', 15.0, '500-1000mg every 6 hours', '500mg every 6 hours', '4g',
    NULL, 'Hepatotoxicity in overdose', TRUE),
('Ceftriaxone', 'Monocef', 'ANTIBIOTIC', 'INJECTION', '1g', 'IV', 'H1',
    'Cephalosporin allergy', NULL, 50.0, '1-2g once daily', '1g once daily', '4g',
    NULL, 'Diarrhea, injection site pain', TRUE),
('Ondansetron', 'Emeset', 'ANTIEMETIC', 'TABLET', '4mg', 'Oral', 'H1',
    'QT prolongation', NULL, 0.15, '4-8mg twice daily', '4mg twice daily', '16mg',
    NULL, 'Headache, constipation', TRUE),
('Entecavir', 'Baraclude', 'ANTIVIRAL', 'TABLET', '0.5mg', 'Oral', 'H1',
    'Pregnancy', NULL, NULL, '0.5mg once daily', '0.5mg once daily', '1mg',
    'Take on empty stomach', 'Fatigue, headache', TRUE),
('Tenofovir', 'Viread', 'ANTIVIRAL', 'TABLET', '300mg', 'Oral', 'H1',
    'Renal impairment', NULL, NULL, '300mg once daily', '300mg once daily', '300mg',
    NULL, 'Renal impairment, bone density loss', TRUE),
('Silymarin', 'Livomyn', 'HEPATOPROTECTIVE', 'CAPSULE', '140mg', 'Oral', NULL,
    NULL, NULL, NULL, '140mg thrice daily', '140mg twice daily', '420mg',
    NULL, 'GI upset', TRUE),
('Vitamin B Complex', 'Becosules', 'VITAMIN_SUPPLEMENT', 'CAPSULE', NULL, 'Oral', NULL,
    NULL, NULL, NULL, '1 capsule once daily', '1 capsule once daily', '1 capsule',
    NULL, 'Rare GI upset', TRUE),
('Vitamin K', 'Konakion', 'VITAMIN_SUPPLEMENT', 'INJECTION', '10mg', 'IV', NULL,
    NULL, 'Warfarin', NULL, '10mg IV once', '10mg IV once', '10mg',
    NULL, 'Injection site reaction', TRUE),
('Spironolactone', 'Aldactone', 'DIURETIC', 'TABLET', '100mg', 'Oral', 'H1',
    'Hyperkalemia, Addison''s disease', 'ACE inhibitors', 1.0, '100-200mg once daily', '50mg once daily', '400mg',
    NULL, 'Hyperkalemia, gynecomastia', TRUE),
('Furosemide', 'Lasix', 'DIURETIC', 'TABLET', '40mg', 'Oral', 'H1',
    'Anuria', NULL, 1.0, '40mg once daily', '20mg once daily', '160mg',
    NULL, 'Hypokalemia, dehydration', TRUE),
('Human Albumin', 'Albuminar', 'ALBUMIN', 'IV', '20%', 'IV', 'H1',
    'Severe anemia, cardiac failure', NULL, NULL, '100ml IV infusion', '100ml IV infusion', '200ml',
    NULL, 'Fluid overload', TRUE),
('Fresh Frozen Plasma', 'FFP', 'BLOOD_PRODUCT', 'IV', '200ml', 'IV', NULL,
    'IgA deficiency', NULL, NULL, 'As per clinical requirement', 'As per clinical requirement', '4 units',
    NULL, 'Transfusion reaction', TRUE),
('Lactulose', 'Duphalac', 'LAXATIVE_OSMOTIC', 'SYRUP', '10g/15ml', 'Oral', NULL,
    'Galactosemia', NULL, NULL, '15-30ml twice daily', '15ml twice daily', '60ml',
    NULL, 'Flatulence, cramping', TRUE),
('ORS', 'Electral', 'ORS', 'SYRUP', '21.8g/sachet', 'Oral', NULL,
    NULL, NULL, NULL, '1 sachet per loose stool', '1 sachet per loose stool', '6 sachets',
    NULL, 'Rare if over-consumed', TRUE),
('Lactobacillus', 'Vizylac', 'PROBIOTIC', 'CAPSULE', NULL, 'Oral', NULL,
    NULL, NULL, NULL, '1 capsule twice daily', '1 capsule twice daily', '2 capsules',
    NULL, 'Rare GI upset', TRUE),
('Loperamide', 'Imodium', 'ANTIDIARRHEAL', 'TABLET', '2mg', 'Oral', 'H1',
    'Bloody diarrhea, bacterial colitis', NULL, NULL, '2mg after each loose stool', '2mg after each loose stool', '16mg',
    NULL, 'Constipation, drowsiness', TRUE),
('Zinc Sulfate', 'Zincovit', 'ZINC_SUPPLEMENT', 'SYRUP', '20mg/5ml', 'Oral', NULL,
    NULL, NULL, NULL, '10ml once daily', '10ml once daily', '20ml',
    NULL, 'GI upset', TRUE),
('Ispaghula Husk', 'Fybogel', 'LAXATIVE_BULK_FORMING', 'SYRUP', '3.5g/sachet', 'Oral', NULL,
    'Intestinal obstruction', NULL, NULL, '1 sachet twice daily', '1 sachet twice daily', '2 sachets',
    'Take with plenty of water', 'Bloating, flatulence', TRUE),
('Bisacodyl', 'Dulcolax', 'LAXATIVE_STIMULANT', 'TABLET', '5mg', 'Oral', NULL,
    'Intestinal obstruction', NULL, NULL, '5-10mg at night', '5mg at night', '10mg',
    NULL, 'Abdominal cramps', TRUE),
('Dicyclomine', 'Cyclopam', 'ANTISPASMODIC', 'TABLET', '20mg', 'Oral', 'H1',
    'Glaucoma, myasthenia gravis', NULL, NULL, '20mg thrice daily', '10mg thrice daily', '80mg',
    NULL, 'Dry mouth, blurred vision', TRUE),
('Amitriptyline', 'Tryptomer', 'ANTIDEPRESSANT', 'TABLET', '10mg', 'Oral', 'H1',
    'Recent myocardial infarction', 'MAO inhibitors', NULL, '10-25mg at night', '10mg at night', '50mg',
    NULL, 'Drowsiness, dry mouth', TRUE),
('Morphine', 'MST Continus', 'PALLIATIVE_CARE', 'TABLET', '10mg', 'Oral', 'X',
    'Respiratory depression', 'Benzodiazepines', NULL, '10mg every 12 hours', '5mg every 12 hours', '60mg',
    NULL, 'Constipation, respiratory depression, sedation', TRUE),
('Protein Powder', 'Protinex', 'NUTRITIONAL_SUPPORT', 'SYRUP', NULL, 'Oral', NULL,
    NULL, NULL, NULL, '2 scoops twice daily', '2 scoops twice daily', '4 scoops',
    NULL, 'Rare GI upset', TRUE),
('Clopidogrel', 'Plavix', 'OTHER', 'TABLET', '75mg', 'Oral', 'H1',
    'Active bleeding', 'Omeprazole', NULL, '75mg once daily', '75mg once daily', '75mg',
    NULL, 'Bleeding risk, bruising', TRUE),
('Capecitabine', 'Xeloda', 'CHEMOTHERAPY', 'TABLET', '500mg', 'Oral', 'X',
    'Severe renal impairment, pregnancy', '5-FU based regimens', NULL, '1250mg/m2 twice daily', '1000mg/m2 twice daily', '2500mg/m2',
    'Take within 30 minutes after food', 'Hand-foot syndrome, diarrhea', TRUE);

CREATE TABLE prescriptions (
    id                  BIGINT AUTO_INCREMENT PRIMARY KEY,
    patient_upid        VARCHAR(20)     NOT NULL,
    visit_id            BIGINT          NULL,
    admission_id        BIGINT          NULL,
    prescribed_date     DATE            NOT NULL,
    doctor_name         VARCHAR(255)    NOT NULL,
    digital_signature   VARCHAR(1000)   NOT NULL,
    signature_hash      VARCHAR(100)    NOT NULL,
    template_used       VARCHAR(30)     NULL,

    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by           VARCHAR(100)    NULL,
    updated_by           VARCHAR(100)    NULL,

    CONSTRAINT fk_prescriptions_patient FOREIGN KEY (patient_upid) REFERENCES patients (upid)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE INDEX idx_prescriptions_patient_upid ON prescriptions (patient_upid);

CREATE TABLE prescription_items (
    prescription_id                BIGINT          NOT NULL,
    drug_id                         BIGINT          NOT NULL,
    generic_name                    VARCHAR(255)    NOT NULL,
    dosage                          VARCHAR(100)    NOT NULL,
    frequency                       VARCHAR(100)    NOT NULL,
    route                           VARCHAR(50)     NULL,
    duration_days                   INT             NULL,
    food_instruction                VARCHAR(20)     NULL,
    generated_instructions          VARCHAR(500)    NULL,
    refills_allowed                 INT             NULL,
    refills_used                    INT             NULL,
    calculated_pediatric_dose_mg    DOUBLE          NULL,

    CONSTRAINT fk_prescription_items_prescription FOREIGN KEY (prescription_id) REFERENCES prescriptions (id) ON DELETE CASCADE,
    CONSTRAINT fk_prescription_items_drug FOREIGN KEY (drug_id) REFERENCES drugs (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
